---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cem-auth
  namespace: staging
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cem-auth
  targetCPUUtilizationPercentage: 80
...