apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: staging
  labels:
    app.kubernetes.io/name: nacos
    app.kubernetes.io/version: "2.0.3"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: staging
    app.kubernetes.io/component: srad
data:
  application.properties: |
    server.port=8848
    spring.datasource.platform=mysql
    db.num=1
    db.url=
    db.user=
    db.password.0=
    db.pool.config.connectionTimeout=30000
    db.pool.config.validationTimeout=10000
    db.pool.config.maximumPoolSize=20
    db.pool.config.minimumIdle=2
    nacos.naming.empty-service.auto-clean=true
    nacos.naming.empty-service.clean.initial-delay-ms=50000
    nacos.naming.empty-service.clean.period-time-ms=30000
    management.metrics.export.elastic.enabled=false
    management.metrics.export.influx.enabled=false
    server.tomcat.accesslog.enabled=true
    server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i
    server.tomcat.basedir=
    nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**
    nacos.core.auth.system.type=nacos
    nacos.core.auth.enabled=false
    nacos.core.auth.default.token.expire.seconds=18000
    nacos.core.auth.default.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789
    nacos.core.auth.caching.enabled=true
    nacos.core.auth.enable.userAgentAuthWhite=true
    nacos.core.auth.server.identity.key=
    nacos.core.auth.server.identity.value=
    nacos.istio.mcp.server.enabled=false
