apiVersion: v1
kind: "Service"
metadata:
  name: alertmanager
  namespace: kube-monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: "v2.4.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: ams
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: "v2.4.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: ams
  ports:
    - name: alertmanager
      protocol: TCP
      port: 9093
      targetPort: 9093
