---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: "8.4.6"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: dashboard
spec:
  type: NodePort
  externalIPs:
    -
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: "8.4.6"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: dashboard
  ports:
    - name: server
      port: 31000
      targetPort: 3000
      protocol: TCP
...