---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cem-gateway
  namespace: dev
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cem-gateway
  targetCPUUtilizationPercentage: 80
...