---
apiVersion: v1
kind: Service
metadata:
  name: cem-answer-web
  namespace: pre
  labels:
    app.kubernetes.io/name: cem-answer-web
    app.kubernetes.io/release: beta
    app.kubernetes.io/track: nightly
    app.kubernetes.io/component: webserver
    app.kubernetes.io/tier: frontend
    app.kubernetes.io/runtime: javascript
    app.kubernetes.io/enviroment: pre
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cem-answer-web
    app.kubernetes.io/release: beta
    app.kubernetes.io/track: nightly
    app.kubernetes.io/component: webserver
    app.kubernetes.io/tier: frontend
    app.kubernetes.io/runtime: javascript
    app.kubernetes.io/enviroment: pre
  ports:
    - name: server
      port: 80
      targetPort: 80
      protocol: TCP