---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cem-auth-logs
  namespace: dev
spec:
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 500Mi
    limits:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
...