---
apiVersion: v1
kind: Service
metadata:
  name: cem-nginx
  namespace: dev
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: "1.19.9.1"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: dev
    app.kubernetes.io/component: proxy-server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: "1.19.9.1"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: dev
    app.kubernetes.io/component: proxy-server
  externalIPs:
    - 192.168.1.77
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 443