---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cem-console
  namespace: pre
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cem-console
  targetCPUUtilizationPercentage: 80
...