---
apiVersion: v1
kind: Service
metadata:
  name: cem-crontab
  namespace: dev
  labels:
    app.kubernetes.io/name: cem-crontab
    app.kubernetes.io/release: beta
    app.kubernetes.io/track: nightly
    app.kubernetes.io/component: microservices
    app.kubernetes.io/tier: backend
    app.kubernetes.io/runtime: java
    app.kubernetes.io/enviroment: dev
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cem-crontab
    app.kubernetes.io/release: beta
    app.kubernetes.io/track: nightly
    app.kubernetes.io/component: microservices
    app.kubernetes.io/tier: backend
    app.kubernetes.io/runtime: java
    app.kubernetes.io/enviroment: dev
  ports:
    - name: server
      port: 80
      targetPort: 8105
      protocol: TCP
    - name: xxl-job
      port: 9999
      targetPort: 9999
      protocol: TCP
