---
apiVersion: v1
kind: Service
metadata:
  name: skywalking
  namespace: kube-monitoring
  labels:
    app.kubernetes.io/name: skywalking
    app.kubernetes.io/version: "8.9.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: apm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: skywalking
    app.kubernetes.io/version: "8.9.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: apm
  ports:
    - name: in
      port: 11800
      targetPort: 11800
      protocol: TCP
    - name: out
      port: 12800
      targetPort: 12800
      protocol: TCP
...
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  namespace: kube-monitoring
  labels:
    app.kubernetes.io/name: skywalking
    app.kubernetes.io/version: "8.9.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: apm
spec:
  type: NodePort
  externalIPs:
    -
  selector:
    app.kubernetes.io/name: skywalking
    app.kubernetes.io/version: "8.9.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: apm
  ports:
    - name: dashboard
      port: 8080
      targetPort: 8080
      protocol: TCP
...