---
apiVersion: v1
kind: Service
metadata:
  name: cem-main
  namespace: staging
  labels:
    app.kubernetes.io/name: cem-main
    app.kubernetes.io/release: beta
    app.kubernetes.io/track: nightly
    app.kubernetes.io/component: webserver
    app.kubernetes.io/tier: frontend
    app.kubernetes.io/runtime: javascript
    app.kubernetes.io/enviroment: staging
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cem-main
    app.kubernetes.io/release: beta
    app.kubernetes.io/track: nightly
    app.kubernetes.io/component: webserver
    app.kubernetes.io/tier: frontend
    app.kubernetes.io/runtime: javascript
    app.kubernetes.io/enviroment: staging
  ports:
    - name: server
      port: 80
      targetPort: 80
      protocol: TCP