---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cem-main
  namespace: dev
  labels:
    app.kubernetes.io/name: cem-main
    app.kubernetes.io/release: beta
    app.kubernetes.io/track: nightly
    app.kubernetes.io/component: webserver
    app.kubernetes.io/tier: frontend
    app.kubernetes.io/runtime: javascript
    app.kubernetes.io/enviroment: dev
data:
  default.conf:  |
    server {
        listen 80;
        server_name xxxxxxxx;
        access_log /dev/stdout json;
        error_log /dev/stdout warn;
        root /app;

        location ~* \.(html|js|css|gif|jpg|jpeg|png|bmp|swf)$ {
            add_header Cache-Control  max-age=no-cache;
            add_header Pragma no-cache;
            add_header Expires 0;
        }

        location / {
            index index.html index.htm index.jsp;
            try_files $uri $uri/ @router;
        }

        location @router {
            rewrite ^.*$ /index.html last;
        }

        location /healthz {
            access_log off;
            allow 127.0.0.1;
            deny all;
            return 200;
        }
    }
...