---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: pre
  labels:
    app.kubernetes.io/name: nacos
    app.kubernetes.io/version: "2.0.3"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: pre
    app.kubernetes.io/component: srad
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: nacos
    app.kubernetes.io/version: "2.0.3"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: pre
    app.kubernetes.io/component: srad
  ports:
    - name: server
      port: 8848
      targetPort: 8848
      protocol: TCP
...
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-external
  namespace: pre
  labels:
    app.kubernetes.io/name: nacos
    app.kubernetes.io/version: "2.0.3"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: pre
    app.kubernetes.io/component: srad
spec:
  type: NodePort
  externalIPs:
    -
  selector:
    app.kubernetes.io/name: nacos
    app.kubernetes.io/version: "2.0.3"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: pre
    app.kubernetes.io/component: srad
  ports:
    - name: server
      port: 8848
      targetPort: 8848
      protocol: TCP
...