---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cem-h5
  namespace: dev
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cem-h5
  targetCPUUtilizationPercentage: 80
...