---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: xxl-job
  namespace: pre
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xxl-job
  targetCPUUtilizationPercentage: 80
...