---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dev
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/enviroment: dev
    app.kubernetes.io/version: "5.7.31"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cem
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
...
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: dev
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/enviroment: dev
    app.kubernetes.io/version: "5.7.31"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cem
subsets:
  - addresses:
      - ip:
    ports:
      - name: mysql
        port: 3306
        protocol: TCP
...