---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dev
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/enviroment: dev
    app.kubernetes.io/version: "4.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cem
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: dev
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/enviroment: dev
    app.kubernetes.io/version: "4.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cem
subsets:
  - addresses:
      - ip:
    ports:
      - name: redis
        port: 6379
        protocol: TCP
...