apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: kube-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: "v2.34.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: tsdb
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - path_prefix: '/'
          static_configs:
            - targets: ['alertmanager:9093']
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'apiserver'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: ['__meta_kubernetes_namespace', '__meta_kubernetes_service_name', '__meta_kubernetes_endpoint_port_name']
            action: keep
            regex: default;kubernetes;https
          - target_label: __address__
            replacement: kubernetes.default.svc:443
      - job_name: 'node'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - regex: __meta_kubernetes_node_label_(.+)
            action: labelmap
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: ['__meta_kubernetes_node_name']
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics
      - job_name: 'cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - regex: __meta_kubernetes_node_label_(.+)
            action: labelmap
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: ['__meta_kubernetes_node_name']
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      - job_name: 'pod'
        scheme: http
        scrape_interval: 5s
        kubernetes_sd_configs:
          - api_server: ~
            role: pod
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_annotation_prometheus_io_scrape']
            regex: true
            action: keep
          - source_labels: ['__meta_kubernetes_pod_annotation_prometheus_io_path']
            action: replace
            regex: (.+)
            target_label: __metrics_path__
          - source_labels: ['__address__', '__meta_kubernetes_pod_annotation_prometheus_io_port']
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - regex: __meta_kubernetes_pod_label_app_kubernetes_io_(.+)
            action: labelmap
          - source_labels: ['__meta_kubernetes_namespace']
            action: replace
            target_label: kubernetes_namespace
          - source_labels: ['__meta_kubernetes_pod_name']
            action: replace
            target_label: kubernetes_pod_name

