---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: "v2.34.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: tsdb
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: "v2.34.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: tsdb
  ports:
    - name: server
      port: 9090
      targetPort: 9090
      protocol: TCP
...
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: kube-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: "v2.34.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: tsdb
spec:
  type: NodePort
  externalIPs:
    -
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: "v2.34.0"
    app.kubernetes.io/tier: middleware
    app.kubernetes.io/enviroment: kube-monitoring
    app.kubernetes.io/component: tsdb
  ports:
    - name: server
      port: 9090
      targetPort: 9090
      protocol: TCP
...