---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cem-message
  namespace: staging
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cem-message
  targetCPUUtilizationPercentage: 80
...