---
apiVersion: v1
kind: Service
metadata:
  name: cem-web
  namespace: staging
  labels:
    app.kubernetes.io/name: cem-web
    app.kubernetes.io/release: beta
    app.kubernetes.io/track: nightly
    app.kubernetes.io/component: microservices
    app.kubernetes.io/tier: backend
    app.kubernetes.io/runtime: java
    app.kubernetes.io/enviroment: staging
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cem-web
    app.kubernetes.io/release: beta
    app.kubernetes.io/track: nightly
    app.kubernetes.io/component: microservices
    app.kubernetes.io/tier: backend
    app.kubernetes.io/runtime: java
    app.kubernetes.io/enviroment: staging
  ports:
    - name: server
      port: 80
      targetPort: 8101
      protocol: TCP